### ISSUE TITLE
Definitions in [HTML] have moved, breaking `alternate`

### ISSUE THREAD

**Issue by jyasskin** [protocol-registries/link-relations#22]
* Relation Name: alternate
* Requested Change(s): The registry points to http://www.w3.org/TR/html5/links.html#link-type-alternate, but the definition is actually at https://html.spec.whatwg.org/multipage/links.html#rel-alternate. It looks like all the other HTML link types, while pointing to http://www.w3.org/TR/html5/links.html, have the right anchor, so the redirect to https://html.spec.whatwg.org/multipage/links.html works.
* Your relationship to the original registrant: None

**Comment by mnot** [comment]
I feel like that might be an oversight in HTML -- if all of the relation types except for one has a particular form of link target?

@annevk?

Overall though, yes, we should update the links to point to WHATWG HTML.

**Comment by annevk** [comment]
The others are derived from the heading. This one had its own ID since 2010: https://github.com/whatwg/html/commit/cd22a8fb22ae0a8d3c3f9fa4940260ba5e8dc0dd. I guess the W3C regressed that at some point. I'll see if others are okay with supporting both.

**Comment by annevk** [comment]
That was a bit more involved than one would hope for, but link-type-alternate is a supported alternative ID now.

**Comment by mnot** [comment]
Request sent to IANA:

Please update the specification references for following entries in the Link Relation Types registry as follows:

- alternate
- author
- bookmark
- external
- help
- icon
- modulepreload
- next
- nofollow
- noopener
- noreferrer
- opener
- prev
- stylesheet
- tag

In each case, the specification reference should be prefixed 'https://html.spec.whatwg.org/multipage/links.html#' instead of 'http://www.w3.org/TR/html5/links.html#' (please retain the suffix, e.g., 'https://html.spec.whatwg.org/multipage/links.html#link-type-alternate').

Note that the reference text for 'help' is incorrect; it should be [html] not [HTML 4.01 Specification].
